{{ cookiecutter.project_slug }}:
  token: changeme
  debug: false
  download_dir: /tmp/{{ cookiecutter.project_slug }}
  env: development
  url: https://{{ cookiecutter.project_slug }}.yourdomain.com
sentry:
  url: null
  environment: development
fastapi:
  cors:
    allow_origin_regex: "^.*$"
    allow_origins:
      - 'http://localhost:8080'
      - 'http://localhost:8000'
      - 'http://localhsot'
    allow_credentials: false
    allow_methods:
      - "*"
    allow_headers:
      - "*"
  middlewares: [] # ['cors', 'tokenAuth']
