apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.project_slug}}
  labels:
    app.kubernetes.io/name: {{cookiecutter.project_slug}}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    name: http
  selector:
    app.kubernetes.io/name: {{cookiecutter.project_slug}}
