apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{cookiecutter.project_slug}}
  labels:
    app.kubernetes.io/name: {{cookiecutter.project_slug}}
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: {{cookiecutter.project_slug}}
